### ISSUE TITLE
Running `teams` for the first time will execute the `while` indefinitely

### ISSUE THREAD

**Issue by turicas** [acran/teams-in-docker#1]
After running `install.sh` and then `teams` on my terminal, I got these messages:

![2021-08-05_14-28-16](https://user-images.githubusercontent.com/186126/128394676-9ae9a703-b7da-424e-8b15-1b0c790c1ff7.png)

The output was huge and I couldn't check if there was a different error in the beginning that caused all these ones.

**Comment by acran** [comment]
@turicas thanks for reporting this!

Since you said this happened when running the first time (and only then?) I guess what happened was that [creating the FIFO for `xdg-open`](https://github.com/acran/teams-in-docker/blob/0a1325c756c830e04f50f4d1ac8c5de0f0971f77/teams.sh#L11) failed since the parent directory was not yet created by `x11docker`.

And because that FIFO was then missing the `read` in the loop would fail immediately but loop nevertheless.

So this should be fixed with the last two commits now.
