### ISSUE TITLE
I am getting : :electron_main_delegate.cc(265)] Running as root without --no-sandbox is not supported

### ISSUE THREAD

**Issue by sant527** [acran/teams-in-docker#5]
$ docker run teams                                                                                                            
[7:0325/041606.158257:FATAL:electron_main_delegate.cc(265)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap (core dumped)

**Comment by acran** [comment]
@sant527: the created image is not meant to be run manually but using `x11docker` and teams requires some capabilities by default that are dropped by `docker`.

This requires the image to be either started with added capabilities / in `privileged` mode or passing respective command line flags to teams. If you want to start the container manually you can find the command line used in this project here:
https://github.com/acran/teams-in-docker/blob/2d5232bfc4a7e1afe8e2404f5aaf1505fe540f80/teams.sh#L22

Otherwise the easiest way to start `teams-in-docker` is using the [`teams.sh` script](https://github.com/acran/teams-in-docker/blob/master/teams.sh).

See the [Readme](https://github.com/acran/teams-in-docker#readme) or the [`install.sh` script](https://github.com/acran/teams-in-docker/blob/master/install.sh) on how to install the scripts for even deeper/more seamless desktop integration.
