### ISSUE TITLE
Linux app discontinued

### ISSUE THREAD

**Issue by Celelibi** [acran/teams-in-docker#9]
It looks like the Linux app has been discontinued and replaced with a "better working" web app.
https://www.microsoft.com/en-us/microsoft-teams/download-app

If this project remains active, I suggest it might instead install chromium inside the container and run it with the teams URL by default.
If it exists, it would be nice to run it with some options/config to make it behave like a standalone app instead of a tab in a browser.

Best regards,
Celelibi

**Comment by acran** [comment]
Thank you for the notice.

This is correct, the official Linux client was discontinued by Microsoft. The `docker` image in this repository now can't even build anymore since the download link for the `deb` is defunct.

The officially supported version for Linux is now the new PWA.
Since my motivation for this project was to isolate an untrusted app and limit its access on my host system and as a PWA it is now sufficiently isolated by the browser - which is good enough for me -  I will now archive this project.

Thanks everyone who used and contributed to it :)
